export const ACTION_TYPES = {
    LOGIN_USER: "LOGIN_USER",
    GET_USER: "GET_USER",
    CREATE_USER: "CREATE_USER",
    LOGOUT: "LOGOUT",
    GET_ALL_USER: "GET_ALL_USER",

    GET_ROOMS: "GET_ROOMS",
    ADD_ROOM: "ADD_ROOM",
    REMOVE_ROOM: "REMOVE_ROOM",

    ADD_MESSAGE: "ADD_MESSAGE",
    GET_MESSAGE: "GET_MESSAGE"
};